### PR TITLE
check if namespace exist or not before creating resources in federation enable

### LINKED ISSUE #656: Kubefed2 enable with wrong federation namespace leaves federated type half created
**What happened**:
`kubefed2 enable Namespace` was run on a cluster where the federation-namespace was not `federation-system` as expected by default.

Output was 
```
$ kubefed2 enable -v 2 Namespaces
I0315 09:23:47.528247   17456 enable.go:199] Found resource "namespaces.core/v1"
customresourcedefinition.apiextensions.k8s.io/federatednamespaces.types.federation.k8s.io created
F0315 09:23:48.024766   17456 enable.go:109] error: Error creating FederatedTypeConfig "namespaces": namespaces "federation-system" not found
```
Attempting to then `enable` `Namespace` with the right `federation-namespace` fails:
```
$ kubefed2 enable -v 2 Namespaces --federation-namespace=my-federation
I0315 09:24:18.161717   17508 enable.go:199] Found resource "namespaces.core/v1"
F0315 09:24:18.456461   17508 enable.go:109] error: Error creating CRD "federatednamespaces.types.federation.k8s.io": customresourcedefinitions.apiextensions.k8s.io "federatednamespaces.types.federation.k8s.io" already exists

```
Attempting to then `disable` Namespace fails:
```
$ kubefed2 disable -v 2 Namespaces 
F0315 10:16:25.640939   18831 disable.go:93] error: Error retrieving FederatedTypeConfig "federation-system/Namespaces": federatedtypeconfigs.core.federation.k8s.io "Namespaces" not found
```

**What you expected to happen**:
Sanity checking by `kubefed2 enable` to avoid creating artifacts on a system that it will later refuse to manage.

**How to reproduce it (as minimally and precisely as possible)**:
Install federation in a non-standard NS, e.g. `my-federation`
`kubefed2 enable Namespace`

**Anything else we need to know?**:
Work around:
```
kubectl delete crd federatednamespaces.types.federation.k8s.io
kubefed2 --federation-namespace=my-federation enable Namespace 
```
**Environment**:
- Kubernetes version (use `kubectl version`)
- Federation version
- Install method (helm vs script)
- Install configuration (namespaced vs cluster-scoped)
- Others

/kind bug

### PR DESCRIPTION
**Pull request by xunpan**
check in `CreateResources` to make `dry-run` succeed even there is no namespace. It is not hard dependecy for `dry-run`

Fixes #656

### CODE REVIEW

File: pkg/kubefed2/enable/enable.go [hunk 1]
```diff
@@ -231,6 +231,15 @@ func CreateResources(cmdOut io.Writer, config *rest.Config, resources *typeResou
 		}
 	}
 
+	hostClientset, err := util.HostClientset(config)
+	if err != nil {
+		return errors.Wrap(err, "Failed to create host clientset")
+	}
+	_, err = hostClientset.CoreV1().Namespaces().Get(namespace, metav1.GetOptions{})
+	if err != nil {
```
Comment (marun) [inline pkg/kubefed2/enable/enable.go]: Please use different error messages for NotFound and other errors, e.g.

```
// IsNotFound
Federation system namespace %q does not exist.
// !IsNotFound
Error attempting to determine whether federation system namepace exists.
```

File: pkg/kubefed2/enable/enable.go [hunk 2]
```diff
@@ -231,6 +231,17 @@ func CreateResources(cmdOut io.Writer, config *rest.Config, resources *typeResou
...
 
+	hostClientset, err := util.HostClientset(config)
+	if err != nil {
+		return errors.Wrap(err, "Failed to create host clientset")
+	}
+	_, err = hostClientset.CoreV1().Namespaces().Get(namespace, metav1.GetOptions{})
+	if apierrors.IsNotFound(err) {
+		return errors.Wrapf(err, "Federation system namespace %q does not exist", namespace)
+	} else if err != nil {
+		return errors.Wrapf(err, "Error attempting to determine whether federation system namepace %q exists", namespace)
```
Comment (marun) [inline pkg/kubefed2/enable/enable.go]: nit: s/namepace/namespace/

**Comment by marun** [comment]
@xunpan Please add a comment after you force-push so that I know to re-review.  I get notified for comments but not for pushes.

**Comment by xunpan** [comment]
Addressed. @marun

**Comment by marun** [comment]
Great, thank you!

/lgtm
/approve
