### PR TITLE
Fix CI fail when there has daemon.json already

### LINKED ISSUE #756: CI failed in configure registry
**Which test(s) are failing**:
`Configuring container registry on host`

**Since when has it been failing**:
yesterday as far as I know

**Reason for failure**:
It seems CI environment issue.

**Anything else we need to know**:
```
Configuring container registry on host
Error: /etc/docker/daemon.json exists and CONFIGURE_INSECURE_REGISTRY=y. This script needs to add an 'insecure-registries' entry with host '172.17.0.1:5000' to /etc/docker/daemon.json. Please make the necessary changes or backup and try again.
The command "test $DOC_ONLY && echo "Skipped!" || DOWNLOAD_BINARIES=y bash -x ./scripts/pre-commit.sh" exited with 1.
```

/kind failing-test

### PR DESCRIPTION
**Pull request by xunpan**
CI fails because daemon.json exists. It may be related to CI environment change. But logically, it is not good to fail if the file exists. If exists, we only need to add our own configuration instead of reporting error.

Fixes #756

### CODE REVIEW

File: scripts/create-clusters.sh [hunk 1]
```diff
@@ -38,12 +38,13 @@ function create-insecure-registry() {
...
   local err=
   if sudo test -f "${docker_daemon_config}"; then
-    echo <<EOF "Error: ${docker_daemon_config} exists and \
-CONFIGURE_INSECURE_REGISTRY=${CONFIGURE_INSECURE_REGISTRY}. This script needs \
-to add an 'insecure-registries' entry with host '${CONTAINER_REGISTRY_HOST}' to \
-${docker_daemon_config}. Please make the necessary changes or backup and try again."
+    if sudo grep -q 'insecure-registries' ${docker_daemon_config}; then
+      echo <<EOF "Error: ${docker_daemon_config} exists and \
+is already configured with an 'insecure-registries' entry. \
+Please make sure it is removed and try again."
```
Comment (shashidharatd) [inline scripts/create-clusters.sh]: (suggestion) Most probably the `insecure-registries entry` is added by our own script in local environment. In Such cases the entry could be correct. if so, just continue the work. otherwise report error about correcting insecure-registries entry.

Comment (xunpan) [reply scripts/create-clusters.sh]: make sense. 

My fix is to check if the `insecure-registries` is set exactly by our own script or not.
If yes, just return success. If not, print error message.

File: scripts/create-clusters.sh [hunk 2]
```diff
@@ -38,12 +38,15 @@ function create-insecure-registry() {
...
   if sudo test -f "${docker_daemon_config}"; then
-    echo <<EOF "Error: ${docker_daemon_config} exists and \
-CONFIGURE_INSECURE_REGISTRY=${CONFIGURE_INSECURE_REGISTRY}. This script needs \
-to add an 'insecure-registries' entry with host '${CONTAINER_REGISTRY_HOST}' to \
-${docker_daemon_config}. Please make the necessary changes or backup and try again."
+    if sudo grep -q "\"insecure-registries\": \[\"${CONTAINER_REGISTRY_HOST}\"\]" ${docker_daemon_config}; then
+      return 0
+    else
+      echo <<EOF "Error: ${docker_daemon_config} exists and \
+is already configured with an 'insecure-registries' entry but not set to ${CONTAINER_REGISTRY_HOST}. \
```
Comment (shashidharatd) [inline scripts/create-clusters.sh]: A small problem with the error message now. This branch may also be entered when there is no 'insecure-registries' entry.

**Comment by xunpan** [comment]
CI environment has its own "registry-mirrors" definition in `daemon.json which make our CI failed.

File: scripts/create-clusters.sh (hunk 2 above)
Comment (xunpan) [reply scripts/create-clusters.sh]: done.

**Comment by shashidharatd** [comment]
/lgtm
Thanks @xunpan
