### PR TITLE
Fix unit test issues and run unit tests in ci

### LINKED ISSUE #471: bug: too many API struct format error and test error
**Domain API error:**
see [this](https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/apis/multiclusterdns/v1alpha1/domain_types.go#L36)

format error as follows(`just lack the '"' in the NameServer param`):
```
type Domain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Domain is the DNS zone associated with the federation
	Domain string `json:"domain"`
	// NameServer is the authoritative DNS name server for the federation domain
	NameServer string `json:nameServer,omitempty"`
}
```

**make test error:**
```
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:61:18: actual.Spec undefined (type *"github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:61:42: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:67:27: result.Items[0].Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:67:51: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:72:18: actual.Spec undefined (type *"github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
pkg/apis/multiclusterdns/v1alpha1/domain_types_test.go:72:42: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/multiclusterdns/v1alpha1".Domain has no field or method Spec)
# github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1_test
pkg/apis/core/v1alpha1/federatedcluster_types_test.go:25:2: imported and not used: "github.com/kubernetes-sigs/federation-v2/pkg/controller/util"
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:61:18: actual.Spec undefined (type *"github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:61:42: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:67:27: result.Items[0].Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:67:51: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:72:18: actual.Spec undefined (type *"github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
pkg/apis/core/v1alpha1/federatedservicestatus_types_test.go:72:42: expected.Spec undefined (type "github.com/kubernetes-sigs/federation-v2/pkg/apis/core/v1alpha1".FederatedServiceStatus has no field or method Spec)
# github.com/kubernetes-sigs/federation-v2/pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:32:6: FakeIngressDNSRecords redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:32:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:37:5: ingressdnsrecordsResource redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:37:5
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:39:5: ingressdnsrecordsKind redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:39:5
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:42:6: (*FakeIngressDNSRecords).Get redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:42:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:53:6: (*FakeIngressDNSRecords).List redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:53:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:75:6: (*FakeIngressDNSRecords).Watch redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:75:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:82:6: (*FakeIngressDNSRecords).Create redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_ingressdnsrecord.go:82:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_servicednsrecord.go:32:6: FakeServiceDNSRecords redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterservicednsrecord.go:32:6
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_servicednsrecord.go:37:5: servicednsrecordsResource redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterservicednsrecord.go:37:5
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_servicednsrecord.go:39:5: servicednsrecordsKind redeclared in this block
	previous declaration at pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusterservicednsrecord.go:39:5
pkg/client/clientset/versioned/typed/multiclusterdns/v1alpha1/fake/fake_multiclusteringressdnsrecord.go:82:6: too many errors
```

### PR DESCRIPTION
**Pull request by shashidharatd**
Fixes #471

### CODE REVIEW

**Comment by gyliu513** [comment]
@ganisback

File: scripts/pre-commit.sh [hunk 1]
```diff
@@ -45,6 +45,14 @@ function download-dependencies() {
   ./scripts/download-binaries.sh
 }
 
+function run-unit-tests() {
```
Comment (marun) [inline scripts/pre-commit.sh]: (No action required) Ugh, I think it's gross that these dependencies are required for unit tests.  I think that requirement should be removed at some point.

**Comment by marun** [comment]
@shashidharatd Thank you for doing this.  I had started running unit tests in #484 but avoided fixing the broken tests.  The generated client tests are going to be removed along with the generated clients in the near future, but there is marginal value in retaining the generated api tests (at least for now).

/lgtm
