### PR TITLE
Don't fail without cluster scope.

### LINKED ISSUE #733: kubefed2 aborts when trying to create existing namespace
**What happened**: As a user that has full access to the "dev" namespace, I ran:
```
$ kubefed2 join g10 --host-cluster-context my-cluster --add-to-registry --v=2 --federation-namespace=dev --registry-namespace=dev --limited-scope=true
I0408 17:42:56.477502   19586 join.go:153] Defaulting cluster context to joining cluster name my-cluster
I0408 17:42:56.477627   19586 join.go:165] Args and flags: name my-cluster, host: my-cluster, host-system-namespace: dev, registry-namespace: dev, kubeconfig: , cluster-context: my-cluster, secret-name: , limited-scope: true, dry-run: false
I0408 17:42:56.563811   19586 join.go:219] Performing preflight checks.
I0408 17:42:56.615306   19586 join.go:309] Registering cluster: my-cluster with the cluster registry.
I0408 17:42:56.621253   19586 join.go:386] Updating existing cluster registry cluster my-cluster
I0408 17:42:56.626754   19586 join.go:318] Registered cluster: my-cluster with the cluster registry.
I0408 17:42:56.626774   19586 join.go:240] Creating dev namespace in joining cluster
I0408 17:42:56.627909   19586 join.go:459] Could not create dev namespace: namespaces is forbidden: User "michael" cannot create resource "namespaces" in API group "" at the cluster scope
I0408 17:42:56.627925   19586 join.go:244] Error creating dev namespace in joining cluster: namespaces is forbidden: User "michael" cannot create resource "namespaces" in API group "" at the cluster scope
F0408 17:42:56.627932   19586 join.go:133] error: namespaces is forbidden: User "michael" cannot create resource "namespaces" in API group "" at the cluster scope
```

**What you expected to happen**: kubefed2 would detect that the "dev" namespace already exists and try to use it instead of aborting with an RBAC error.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a namespace, say "dev".
2. Create a user whose RBAC gives full access to resources in the "dev" namespace, but no cluster-level access.
3. Create a namespaced federation installation in the "dev" namespace.
4. Run kubefed2 using the restricted user.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`) ```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Federation version
```
kubefed2 version: version.Info{Version:"v0.0.7-91-gd840a47f-dirty", GitCommit:"d840a47f4243a267b9722fa9a0fed3492f4a7f64", GitTreeState:"dirty", BuildDate:"2019-04-08T22:27:03Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
```
- Install method (helm vs script) scripts/deploy-federation-latest.sh
- Install configuration (namespaced vs cluster-scoped) namespaced
- Others

<!-- DO NOT EDIT BELOW THIS LINE -->
/kind bug

### PR DESCRIPTION
**Pull request by michaelfig**
Fixes #733.

This PR allows the user to have RBAC permissions to the namespaced installation host, but not clusterwide access.  Clusterwide access is still required to join other clusters.

I use this successfully to create federations between my local, namespace-only role, and remote clusterwide roles.

### CODE REVIEW

File: pkg/kubefed2/join.go [hunk 1]
```diff
@@ -450,11 +450,22 @@ func createFederationNamespace(clusterClientset kubeclient.Interface, federation
...
-	if err != nil && !apierrors.IsAlreadyExists(err) {
-		glog.V(2).Infof("Could not create %s namespace: %v", federationNamespace, err)
+	_, err := clusterClientset.CoreV1().Namespaces().Get(federationNamespace, metav1.GetOptions{})
+	if err != nil && !apierrors.IsNotFound(err) {
+		glog.V(2).Infof("Could not get %s namespace: %v", federationNamespace, err)
 		return nil, err
 	}
+
+	if err == nil {
+		glog.V(2).Infof("Already existing %s namespace", federationNamespace)
```
Comment (xunpan) [inline pkg/kubefed2/join.go]: I think we can return here and decrease unnecessary indent for `not found` logic.

File: pkg/kubefed2/join.go [hunk 2]
```diff
@@ -489,19 +500,22 @@ func createRBACSecret(hostClusterClientset, joiningClusterClientset kubeclient.I
...
-
-		err = createHealthCheckClusterRoleAndBinding(joiningClusterClientset, saName, namespace, joiningClusterName,
-			dryRun, errorOnExisting)
-		if err != nil {
-			glog.V(2).Infof("Error creating health check cluster role and binding for service account: %s in joining cluster: %s due to: %v",
-				saName, joiningClusterName, err)
-			return nil, err
-		}
+		if hostClusterName == joiningClusterName {
+			glog.V(2).Infof("Skipping creating health check cluster role and binding for host cluster: %s", hostClusterName)
```
Comment (xunpan) [inline pkg/kubefed2/join.go]: Could you help to explain below questions to me:
 - What is the reason to skip this on host cluster? 
 - This role binding is used for helth check in controller. What is the relationship with the namespace creation case?

**Comment by michaelfig** [comment]
@xunpan, Actually, I did more experimentation, and it looks like a clusterrolebinding is necessary for even namespaced installs.

So, this whole patch is probably irrelevant.

Do you have any thoughts on this?

**Comment by marun** [comment]
@michaelfig A clusterrole is required for the healthcheck.  If your goal is limiting the permissions required to join a cluster, it should be possible to ensure the owner of the target namespace also has GET permission for the clusterrole that `kubefed2 join` would otherwise create.  Provided `join` can verify that the clusterrole is as expected, it wouldn't need further permission.

**Comment by michaelfig** [comment]
Maybe a better approach would be to have `kubefed2 join` have a `--dry-run` mode that could be used to dump the YAML of the changes it would be making?

**Comment by marun** [comment]
@michaelfig I think you're onto something.  Since the behavior of `enable` and `federate` is for `-o yaml` to force dry-run and just output the yaml of what would be applied, I think the same could be done for `join`.  There would just need to be clear separation in the output between resources intended for the host cluster and the joining cluster.

**Comment by xunpan** [comment]
I agree to make `dry-run` things. 

But I think the below message of #733 should be fixed. It seems make no sense to create an existing namespace and tells no permission.
```
F0408 17:42:56.627932   19586 join.go:133] error: namespaces is forbidden: User "michael" cannot create resource "namespaces" in API group "" at the cluster scope
```

File: pkg/kubefed2/join.go (hunk 1 above)
Comment (michaelfig) [reply pkg/kubefed2/join.go]: Done.

File: pkg/kubefed2/join.go (hunk 2 above)
Comment (michaelfig) [reply pkg/kubefed2/join.go]: As discussed, I've removed this part of the PR.

**Comment by michaelfig** [comment]
@xunpan, I've repushed the PR, focused entirely on the namespace creation error (and implementing your recommendations).  Please review.

**Comment by xunpan** [comment]
Sorry for late.

It LGTM. Please squash 2 commits into one. And let's wait for checkings succeed.

**Comment by michaelfig** [comment]
@xunpan, done.

**Comment by xunpan** [comment]
@michaelfig please help to rebase

**Comment by michaelfig** [comment]
Flaky test?

**Comment by marun** [comment]
Transient infrastructure failure related to docker build.   I've restarted it.

**Comment by marun** [comment]
Thank you!

/approve
/lgtm
