### PR TITLE
Increase log level of cluster status ok logs

### LINKED ISSUE #835: Controller log flooded with 'ClusterReady healthz responded with ok' messages
**What happened**:
When increasing log verbosity to `--v=4` in an attempt to debug the `controller-manager` logs, the log is flooded with repeated messages of:
```bash
I0503 17:01:08.153504       1 federated_informer.go:238] Cluster &{{ } {cluster1  federation-system /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster1 42f1367f-6dc2-11e9-84a4-02420ec6818a 128487 1 2019-05-03 16:41:12 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{cluster1} &LocalObjectReference{Name:cluster1-l749b,}} {[{Ready True 2019-05-03 17:00:57 +0000 UTC 2019-05-03 16:55:38 +0000 UTC ClusterReady /healthz responded with ok}] [] }} not updated to &{{ } {cluster1  federation-system /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster1 42f1367f-6dc2-11e9-84a4-02420ec6818a 128504 1 2019-05-03 16:41:12 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{cluster1} &LocalObjectReference{Name:cluster1-l749b,}} {[{Ready True 2019-05-03 17:01:07 +0000 UTC 2019-05-03 16:55:38 +0000 UTC ClusterReady /healthz responded with ok}] [] }} as ready status and specs are identical
I0503 17:01:08.153726       1 federated_informer.go:238] Cluster &{{ } {cluster1  federation-system /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster1 42f1367f-6dc2-11e9-84a4-02420ec6818a 128487 1 2019-05-03 16:41:12 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{cluster1} &LocalObjectReference{Name:cluster1-l749b,}} {[{Ready True 2019-05-03 17:00:57 +0000 UTC 2019-05-03 16:55:38 +0000 UTC ClusterReady /healthz responded with ok}] [] }} not updated to &{{ } {cluster1  federation-system /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster1 42f1367f-6dc2-11e9-84a4-02420ec6818a 128504 1 2019-05-03 16:41:12 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{cluster1} &LocalObjectReference{Name:cluster1-l749b,}} {[{Ready True 2019-05-03 17:01:07 +0000 UTC 2019-05-03 16:55:38 +0000 UTC ClusterReady /healthz responded with ok}] [] }} as ready status and specs are identical
I0503 17:01:08.250060       1 federated_informer.go:238] Cluster &{{ } {cluster1  federation-system /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster1 42f1367f-6dc2-11e9-84a4-02420ec6818a 128487 1 2019-05-03 16:41:12 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{cluster1} &LocalObjectReference{Name:cluster1-l749b,}} {[{Ready True 2019-05-03 17:00:57 +0000 UTC 2019-05-03 16:55:38 +0000 UTC ClusterReady /healthz responded with ok}] [] }} not updated to &{{ } {cluster1  federation-system /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster1 42f1367f-6dc2-11e9-84a4-02420ec6818a 128504 1 2019-05-03 16:41:12 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{cluster1} &LocalObjectReference{Name:cluster1-l749b,}} {[{Ready True 2019-05-03 17:01:07 +0000 UTC 2019-05-03 16:55:38 +0000 UTC ClusterReady /healthz responded with ok}] [] }} as ready status and specs are identical
I0503 17:01:08.350309       1 federated_informer.go:238] Cluster &{{ } {cluster2  federation-system /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster2 430467a2-6dc2-11e9-84a4-02420ec6818a 128488 1 2019-05-03 16:41:12 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{cluster2} &LocalObjectReference{Name:cluster2-lxd8l,}} {[{Ready True 2019-05-03 17:00:57 +0000 UTC 2019-05-03 16:55:38 +0000 UTC ClusterReady /healthz responded with ok}] [] }} not updated to &{{ } {cluster2  federation-system /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster2 430467a2-6dc2-11e9-84a4-02420ec6818a 128503 1 2019-05-03 16:41:12 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{cluster2} &LocalObjectReference{Name:cluster2-lxd8l,}} {[{Ready True 2019-05-03 17:01:07 +0000 UTC 2019-05-03 16:55:38 +0000 UTC ClusterReady /healthz responded with ok}] [] }} as ready status and specs are identical
I0503 17:01:08.350500       1 federated_informer.go:238] Cluster &{{ } {cluster1  federation-system /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster1 42f1367f-6dc2-11e9-84a4-02420ec6818a 128487 1 2019-05-03 16:41:12 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{cluster1} &LocalObjectReference{Name:cluster1-l749b,}} {[{Ready True 2019-05-03 17:00:57 +0000 UTC 2019-05-03 16:55:38 +0000 UTC ClusterReady /healthz responded with ok}] [] }} not updated to &{{ } {cluster1  federation-system /apis/core.federation.k8s.io/v1alpha1/namespaces/federation-system/federatedclusters/cluster1 42f1367f-6dc2-11e9-84a4-02420ec6818a 128504 1 2019-05-03 16:41:12 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{cluster1} &LocalObjectReference{Name:cluster1-l749b,}} {[{Ready True 2019-05-03 17:01:07 +0000 UTC 2019-05-03 16:55:38 +0000 UTC ClusterReady /healthz responded with ok}] [] }} as ready status and specs are identical
```

These appear to be benign `healthz ok` messages, but it makes debugging the log difficult. Consider reducing the verbosity by increasing its log level to something > 4:
https://github.com/kubernetes-sigs/federation-v2/blob/a2b9d8f2b97605efc44fb4cf3821adb0b0fa63ca/pkg/controller/util/federated_informer.go#L238

A logging mechanism with exponential backoff would be ideal.

**What you expected to happen**:
Not have the `controller-manager` log buffer flooded with repeated benign messages.

**How to reproduce it (as minimally and precisely as possible)**:
Launch the controller with `--v=4`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.4
- Federation version: 0.0.9
- Install method (helm vs script): helm
- Install configuration (namespaced vs cluster-scoped): cluster-scoped
- Others

/kind bug

### PR DESCRIPTION
**Pull request by font**
Fixes #835

### CODE REVIEW

File: pkg/controller/util/federated_informer.go [hunk 1]
```diff
@@ -235,7 +235,7 @@ func NewFederatedInformer(
 						}
 					}
 				} else {
-					glog.V(4).Infof("Cluster %v not updated to %v as ready status and specs are identical", oldCluster, curCluster)
+					glog.V(5).Infof("Cluster %v not updated to %v as ready status and specs are identical", oldCluster, curCluster)
```
Comment (marun) [inline pkg/controller/util/federated_informer.go]: Maybe push to 7 - relegate this kind of "I'm doing my job" low-value log to the bottom of the barrel.

Comment (font) [reply pkg/controller/util/federated_informer.go]: Haha, I had it at 6 originally and then lowered it in case somebody would object. :)

**Comment by xunpan** [comment]
Though I don't know why it is 7 but it is lower enough to me for runtime logging for this :-)

/lgtm
