### PR TITLE
always unjoin if any resource is failed in deletion

### LINKED ISSUE #188: `unjoin` should succeed if some resources remove failed.
This is a follow up issue based on comments at https://github.com/kubernetes-sigs/federation-v2/pull/137#issuecomment-406447550

From @marun :  I am still stuck on error handling. Removal of any resource would ideally not fail if not found, ensuring that cleanup of partial configuration is possible.

/assign

### PR DESCRIPTION
**Pull request by xunpan**
Fix #188 

unjoin should always to be executed to be finished if some of resources are failed in
deletion

@gyliu513

### CODE REVIEW

**Comment by xunpan** [comment]
I reproduce this issue as:
1. join
2. unjoin
3. join  // failed if we join just after unjoin operation
Reason reported by join: 
```
error: serviceaccounts "cluster2-cluster1" is forbidden: unable to create new content in namespace federation-system because it is being terminated
```
After that, you canot successfuly join/unjoin the cluster.


The join operation register Cluster to federation controller even it failed in execution. After that, if you want to join the cluster, you should not use  option "--add-to-registry" in join operation. Or else, it failed. This is the root cause.

This fix will make unjoin always clean anything even some resources failed in deletion. After that, you can always join cluster after unjoin it. 

Note: even if you failed in join, you have to unjoin before next join, or remove option "--add-to-registry" from your join command line.

File: pkg/kubefed2/unjoin.go [hunk 1]
```diff
@@ -380,44 +321,38 @@ func deleteServiceAccount(clusterClientset client.Interface, saName,
...
-		return nil
+		return
 	}
 
 	roleName := util.RoleName(saName)
 	commonClusterRoleName := util.CommonClusterRoleName(saName)
 
 	// Attempt to delete all role and role bindings created by join
-	// and ignore if they are missing.
+	// and ignore if there has any error
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: s/has/is/

File: pkg/kubefed2/unjoin.go [hunk 2]
```diff
@@ -281,81 +233,70 @@ func unregisterCluster(crClientset *crclient.Clientset, clusterNamespace, host,
...
 
-	err := deleteClusterRoleAndBinding(unjoiningClusterClientset, saName, namespace, dryRun)
-	if err != nil {
-		glog.V(2).Infof("Error deleting cluster role binding for service account: %s in unjoining cluster: %v",
-			saName, err)
-		return err
-	}
-
+	deleteClusterRoleAndBinding(unjoiningClusterClientset, saName, namespace, dryRun)
 	glog.V(2).Infof("Deleted cluster role binding for service account: %s in unjoining cluster: %s",
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: This message should be logged on success in `deleteClusterRoleAndBinding`.

File: pkg/kubefed2/unjoin.go [hunk 3]
```diff
@@ -281,81 +233,70 @@ func unregisterCluster(crClientset *crclient.Clientset, clusterNamespace, host,
...
 	if err != nil {
-		return nil, err
+		glog.V(2).Infof("Failed to delete Secret resource from namespace: %s for unjoin cluster: %s due to: %v", federationNamespace, unjoiningClusterName, err)
 	}
 
 	err = fedClientset.CoreV1alpha1().FederatedClusters(federationNamespace).Delete(
 		unjoiningClusterName, &metav1.DeleteOptions{})
 	if err != nil {
-		return nil, err
+		glog.V(2).Infof("Failed to delete Secret resource from namespace: %s for unjoin cluster: %s due to: %v", federationNamespace, unjoiningClusterName, err)
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: Refers to Secret when it should be FederatedCluster.

File: pkg/kubefed2/unjoin.go [hunk 4]
```diff
@@ -204,62 +182,36 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, federationNamespace,
...
 
-		err = deleteFedNSFromUnjoinCluster(clusterClientset,
+		deleteFedNSFromUnjoinCluster(clusterClientset,
 			federationNamespace, unjoiningClusterName, hostClusterContext, dryRun)
-		if err != nil {
-			glog.V(2).Infof("Could not delete cluster RBAC resources: %v", err)
-			return err
-		}
-
 		glog.V(2).Infof("Deleted federation namespace: %s from unjoin cluster: %s",
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: This message should be logged on success in `deleteFedNSFromUnjoinCluster`.

File: pkg/kubefed2/unjoin.go [hunk 5]
```diff
@@ -163,39 +161,19 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, federationNamespace,
...
-	_, err = deleteFederatedClusterAndSecret(hostClientset, fedClientset, federationNamespace,
+	deleteFederatedClusterAndSecret(hostClientset, fedClientset, federationNamespace,
 		unjoiningClusterName, dryRun)
-	if err != nil {
-		glog.V(2).Infof("Failed to delete federated cluster resource from namespace: %s for unjoin cluster: %s due to: %v",
-			federationNamespace, unjoiningClusterName, err)
-		return err
-	}
-
 	glog.V(2).Infof("Deleted federated cluster resource from namespace: %s for unjoin cluster: %s",
```
Comment (gyliu513) [inline pkg/kubefed2/unjoin.go]: This also should only be logged if there is no error for `deleteFederatedClusterAndSecret`, so how about keep the return value of `deleteFederatedClusterAndSecret` and only log this message `if err == nil`? Same for other functions.

File: pkg/kubefed2/unjoin.go [hunk 6]
```diff
@@ -163,39 +161,19 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, federationNamespace,
...
 		federationNamespace, unjoiningClusterName)
 
-	err = deleteRBACResources(hostClientset, clusterClientset,
-		federationNamespace, unjoiningClusterName, hostClusterContext, dryRun)
-	if err != nil {
-		glog.V(2).Infof("Could not delete cluster RBAC resources: %v", err)
-		return err
```
Comment (gyliu513) [inline pkg/kubefed2/unjoin.go]: How about keep this error log but only delete `return err`?

**Comment by xunpan** [comment]
@marun, the new commit includes:
1. deletion order changes. If any operations in deleting account+bindings+namespace failed, skip deletion of federated cluster and secret.
2. add force flag to forcely delete federeated cluster and secret resources for the unjoined cluster even there has errors in deletion of account+bindings+namespace
3. update message accordingly to make each operation log error, succeed messages correct.

File: pkg/kubefed2/unjoin.go [hunk 7]
```diff
@@ -163,76 +164,25 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, federationNamespace,
...
 			hostClusterContext, unjoiningClusterContext, federationNamespace)
 	} else {
-		glog.V(2).Infof("Deleting federation namespace: %s from unjoin cluster: %s",
-			federationNamespace, unjoiningClusterName)
-
-		err = deleteFedNSFromUnjoinCluster(clusterClientset,
-			federationNamespace, unjoiningClusterName, hostClusterContext, dryRun)
+		err = deleteFedNSFromUnjoinCluster(clusterClientset, federationNamespace, unjoiningClusterName, dryRun)
 		if err != nil {
-			glog.V(2).Infof("Could not delete cluster RBAC resources: %v", err)
```
Comment (gyliu513) [inline pkg/kubefed2/unjoin.go]: How about keep this message as well?

File: pkg/kubefed2/unjoin.go [hunk 8]
```diff
@@ -65,6 +64,8 @@ func (o *unjoinFederationOptions) Bind(flags *pflag.FlagSet) {
 		"Name of the cluster's context in the local kubeconfig. Defaults to cluster name if unspecified.")
 	flags.BoolVar(&o.removeFromRegistry, "remove-from-registry", false,
 		"Remove the cluster from the cluster registry running in the host cluster context.")
+	flags.BoolVar(&o.forceDeletion, "force", false,
+		"Forcely delete federeated cluster and secret resources for the unjoined cluster.")
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `Delete federated cluster and secret resources even if resources in the cluster targeted for unjoin are not removed successfully`

File: pkg/kubefed2/unjoin.go [hunk 9]
```diff
@@ -163,76 +164,25 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, federationNamespace,
...
-	glog.V(2).Infof("Deleted federated cluster resource from namespace: %s for unjoin cluster: %s",
-		federationNamespace, unjoiningClusterName)
-
-	err = deleteRBACResources(hostClientset, clusterClientset,
-		federationNamespace, unjoiningClusterName, hostClusterContext, dryRun)
-	if err != nil {
-		glog.V(2).Infof("Could not delete cluster RBAC resources: %v", err)
-		return err
-	}
+	isSucceed := deleteRBACResources(clusterClientset, federationNamespace, unjoiningClusterName, hostClusterContext, dryRun)
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/isSucceed/deletionSucceeded/`

`isSucceed` is not grammatically correct in English.

File: pkg/kubefed2/unjoin.go [hunk 10]
```diff
@@ -241,25 +191,24 @@ func performPreflightChecksForUnjoin(clusterClientset client.Interface, name, ho
 // removeFromClusterRegistry handles removing the cluster from the cluster registry and
 // reports progress.
 func removeFromClusterRegistry(hostConfig *rest.Config, clusterNamespace, host, unjoiningClusterName string,
-	dryRun bool) error {
+	dryRun bool) {
 
 	// Get the cluster registry clientset using the host cluster config.
 	crClientset, err := util.ClusterRegistryClientset(hostConfig)
 	if err != nil {
 		glog.V(2).Infof("Failed to get cluster registry clientset: %v", err)
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: Given that the error is no longer returned to be logged by the caller, this log call should be `glog.Errorf` instead of `Infof`.

File: pkg/kubefed2/unjoin.go [hunk 11]
```diff
@@ -241,25 +191,24 @@ func performPreflightChecksForUnjoin(clusterClientset client.Interface, name, ho
...
-		return err
+		return
 	}
 
 	glog.V(2).Infof("Removing cluster: %s from the cluster registry.", unjoiningClusterName)
 
 	err = unregisterCluster(crClientset, clusterNamespace, host, unjoiningClusterName, dryRun)
 	if err != nil {
 		glog.V(2).Infof("Could not remove cluster from the cluster registry: %v", err)
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/glog.V(2).Infof/glog.Errorf/`

File: pkg/kubefed2/unjoin.go [hunk 12]
```diff
@@ -281,81 +230,90 @@ func unregisterCluster(crClientset *crclient.Clientset, clusterNamespace, host,
...
 	}
 
+	glog.V(2).Infof("Deleting federated cluster resource from namespace: %s for unjoin cluster: %s",
+		federationNamespace, unjoiningClusterName)
+
 	fedCluster, err := fedClientset.CoreV1alpha1().FederatedClusters(federationNamespace).Get(
 		unjoiningClusterName, metav1.GetOptions{})
 	if err != nil {
-		return fedCluster, err
+		glog.V(2).Infof("Failed to get FederatedCluster resource from namespace: %s for unjoin cluster: %s due to: %v", federationNamespace, unjoiningClusterName, err)
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/glog.V(2).Infof/glog.Errorf/`

File: pkg/kubefed2/unjoin.go [hunk 13]
```diff
@@ -281,81 +230,90 @@ func unregisterCluster(crClientset *crclient.Clientset, clusterNamespace, host,
...
+		// cannot continue if we lack of FederatedCluster returned
+		return
 	}
 
 	err = hostClientset.CoreV1().Secrets(federationNamespace).Delete(fedCluster.Spec.SecretRef.Name,
 		&metav1.DeleteOptions{})
 	if err != nil {
-		return nil, err
+		glog.V(2).Infof("Failed to delete Secret resource from namespace: %s for unjoin cluster: %s due to: %v", federationNamespace, unjoiningClusterName, err)
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/glog.V(2).Infof/glog.Errorf/`

File: pkg/kubefed2/unjoin.go [hunk 14]
```diff
@@ -281,81 +230,90 @@ func unregisterCluster(crClientset *crclient.Clientset, clusterNamespace, host,
...
+	} else {
+		glog.V(2).Infof("Deleted Secret resource from namespace: %s for unjoin cluster: %s", federationNamespace, unjoiningClusterName)
 	}
 
 	err = fedClientset.CoreV1alpha1().FederatedClusters(federationNamespace).Delete(
 		unjoiningClusterName, &metav1.DeleteOptions{})
 	if err != nil {
-		return nil, err
+		glog.V(2).Infof("Failed to delete FederatedCluster resource from namespace: %s for unjoin cluster: %s due to: %v", federationNamespace, unjoiningClusterName, err)
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/glog.V(2).Infof/glog.Errorf/`

File: pkg/kubefed2/unjoin.go [hunk 15]
```diff
@@ -281,81 +230,90 @@ func unregisterCluster(crClientset *crclient.Clientset, clusterNamespace, host,
...
 }
 
 // deleteRBACResources deletes the cluster role, cluster rolebindings and service account
 // from the unjoining cluster.
-func deleteRBACResources(hostClusterClientset, unjoiningClusterClientset client.Interface,
-	namespace, unjoiningClusterName, hostClusterName string, dryRun bool) error {
+func deleteRBACResources(unjoiningClusterClientset client.Interface,
+	namespace, unjoiningClusterName, hostClusterName string, dryRun bool) bool {
+
+	var isSucceed = true
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/isSucceed/deletionSucceeded/`

File: pkg/kubefed2/unjoin.go [hunk 16]
```diff
@@ -281,81 +230,90 @@ func unregisterCluster(crClientset *crclient.Clientset, clusterNamespace, host,
...
-		saName, unjoiningClusterName)
-
 	glog.V(2).Infof("Deleting service account %s in unjoining cluster: %s", saName, unjoiningClusterName)
 
-	err = deleteServiceAccount(unjoiningClusterClientset, saName, namespace, dryRun)
+	err := deleteServiceAccount(unjoiningClusterClientset, saName, namespace, dryRun)
 	if err != nil {
-		return err
+		isSucceed = false
+		glog.V(2).Infof("Error deleting service account: %s in unjoining cluster. %v", saName, err)
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/glog.V(2).Infof/glog.Errorf/`

File: pkg/kubefed2/unjoin.go (hunk 7 above)
Comment (marun) [reply pkg/kubefed2/unjoin.go]: If the current strategy of returning an error is maintained, I agree that the error needs to be logged (and via `Errorf`).  But why should `deleteFedNSFromUnjoinCluster` return an error?  It would be more consistent to log the error in the function and return an indication of success instead.

File: pkg/kubefed2/unjoin.go [hunk 17]
```diff
@@ -281,81 +230,90 @@ func unregisterCluster(crClientset *crclient.Clientset, clusterNamespace, host,
...
 	if dryRun {
 		return nil
 	}
 
+	glog.V(2).Infof("Deleting federation namespace: %s from unjoin cluster: %s",
+		federationNamespace, unjoiningClusterName)
 	err := unjoiningClusterClientset.CoreV1().Namespaces().Delete(federationNamespace,
 		&metav1.DeleteOptions{})
 	if err != nil {
 		glog.V(2).Infof("Could not delete federation namespace: %s due to: %v", federationNamespace, err)
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: If the strategy of returning an error is used, this log line should be removed and the caller be responsible for logging the error.

If this function stops returning an error and is responsible for logging, `s/glog.V(2).Infof/glog.Errorf/`.

File: pkg/kubefed2/unjoin.go [hunk 18]
```diff
@@ -380,44 +338,46 @@ func deleteServiceAccount(clusterClientset client.Interface, saName,
 // deleteClusterRoleAndBinding deletes an RBAC cluster role and binding that
 // allows the service account identified by saName to access all resources in
 // all namespaces in the cluster associated with clusterClientset.
-func deleteClusterRoleAndBinding(clusterClientset client.Interface, saName, namespace string, dryRun bool) error {
+func deleteClusterRoleAndBinding(clusterClientset client.Interface, saName, namespace string, dryRun bool) bool {
+	var isSucceed = true
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/isSucceed/deletionSucceeded/`

File: pkg/kubefed2/unjoin.go [hunk 19]
```diff
@@ -380,44 +338,46 @@ func deleteServiceAccount(clusterClientset client.Interface, saName,
...
 
 	// Attempt to delete all role and role bindings created by join
-	// and ignore if they are missing.
+	// and ignore if there is any error
 
 	for _, name := range []string{roleName, commonClusterRoleName} {
 		err := clusterClientset.RbacV1().ClusterRoleBindings().Delete(name, &metav1.DeleteOptions{})
 		if err != nil && !errors.IsNotFound(err) {
+			isSucceed = false
 			glog.V(2).Infof("Could not delete cluster role binding %q in unjoining cluster: %v", name, err)
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/glog.V(2).Infof/glog.Errorf/`

File: pkg/kubefed2/unjoin.go [hunk 20]
```diff
@@ -380,44 +338,46 @@ func deleteServiceAccount(clusterClientset client.Interface, saName,
...
-			return err
 		}
 
 		err = clusterClientset.RbacV1().ClusterRoles().Delete(name, &metav1.DeleteOptions{})
 		if err != nil && !errors.IsNotFound(err) {
+			isSucceed = false
 			glog.V(2).Infof("Could not delete cluster role %q in unjoining cluster: %v", name, err)
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/glog.V(2).Infof/glog.Errorf/`

File: pkg/kubefed2/unjoin.go [hunk 21]
```diff
@@ -380,44 +338,46 @@ func deleteServiceAccount(clusterClientset client.Interface, saName,
...
-			return err
 		}
 	}
 
 	err := clusterClientset.RbacV1().RoleBindings(namespace).Delete(roleName, &metav1.DeleteOptions{})
 	if err != nil && !errors.IsNotFound(err) {
+		isSucceed = false
 		glog.V(2).Infof("Could not delete role binding for service account: %s in unjoining cluster: %v",
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/glog.V(2).Infof/glog.Errorf/`

File: pkg/kubefed2/unjoin.go [hunk 22]
```diff
@@ -380,44 +338,46 @@ func deleteServiceAccount(clusterClientset client.Interface, saName,
...
 			saName, err)
-		return err
 	}
 
 	err = clusterClientset.RbacV1().Roles(namespace).Delete(roleName, &metav1.DeleteOptions{})
 	if err != nil && !errors.IsNotFound(err) {
+		isSucceed = false
 		glog.V(2).Infof("Could not delete role for service account: %s in unjoining cluster: %v",
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: `s/glog.V(2).Infof/glog.Errorf/`

File: pkg/kubefed2/unjoin.go [hunk 23]
```diff
@@ -163,76 +164,25 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, federationNamespace,
...
-	sa, err := clusterClientset.CoreV1().ServiceAccounts(federationNamespace).Get(saName,
-		metav1.GetOptions{})
-
-	if errors.IsNotFound(err) {
-		return fmt.Errorf("service account does not exist in unjoining cluster")
-	} else if err != nil {
-		return err
-	} else if sa != nil {
-		return nil
+	// deletionSucceeded when all operations in deleteRBACResources and deleteFedNSFromUnjoinCluster succeed.
```
Comment (gyliu513) [inline pkg/kubefed2/unjoin.go]: Please move this after L171, we should not delete namespace before delete resources in the namespace.

Comment (marun) [reply pkg/kubefed2/unjoin.go]: The namespace in question is in the member cluster targeted for unjoining.  Why should it not be removed first?

File: pkg/kubefed2/unjoin.go (hunk 12 above)
Comment (marun) [inline pkg/kubefed2/unjoin.go]: Oops, missed this one.

File: pkg/kubefed2/unjoin.go [hunk 24]
```diff
@@ -281,81 +230,90 @@ func unregisterCluster(crClientset *crclient.Clientset, clusterNamespace, host,
...
 
+	glog.V(2).Infof("Deleting federated cluster resource from namespace: %s for unjoin cluster: %s",
+		federationNamespace, unjoiningClusterName)
+
 	fedCluster, err := fedClientset.CoreV1alpha1().FederatedClusters(federationNamespace).Get(
 		unjoiningClusterName, metav1.GetOptions{})
 	if err != nil {
-		return fedCluster, err
+		glog.V(2).Infof("Failed to get FederatedCluster resource from namespace: %s for unjoin cluster: %s due to: %v", federationNamespace, unjoiningClusterName, err)
+		// cannot continue if we lack of FederatedCluster returned
```
Comment (marun) [inline pkg/kubefed2/unjoin.go]: nit: This comment is redundant, please remove.

**Comment by marun** [comment]
@xunpan Please collapse into single commit and revise the message to indicate what was done rather than just reference the github issue (as per the majority of commit messages in the tree).  A clean history simplifies the task of future maintainers.

**Comment by marun** [comment]
Thank you!

/approve
/lgtm
